packages:
  - 'packages/**'
  - 'apps/*'
  - 'apps/*/*'
  - '!apps/sdk-infra/.sst'
  - '!apps/sdk-infra/node_modules'
  - '!packages/sdk/.sst'
  - '!packages/sdk/node_modules'
  - '!packages/sdk/client/bundle'
  - '!packages/sdk/common/bundle'
  - 'stacks/**'
  - 'turbo/**'
  - 'external-api/**'
  - '!**/test/**'
  - '!**/.sst/**'
  - '!packages/sdk/simulator/service'
