packages:
  - 'packages/**'
  - 'apps/**'
  - 'sdk'
  - 'sdk/*'
  - 'sdk/*/*'
  - 'sdk/*/*/*'
  - '!sdk/.sst'
  - '!sdk/node_modules'
  - '!packages/sdk/.sst'
  - '!packages/sdk/node_modules'
  - '!packages/sdk/client/bundle'
  - '!packages/sdk/common/bundle'
  - 'stacks/**'
  - 'turbo/**'
  - 'external-api/**'
  - '!**/test/**'
  - '!**/.sst/**'
