/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "CacheTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SdkAuthorizer": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SdkBackendV1x1x0": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SdkBackendV2x3x0": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SdkBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SdkGateway": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "SdkOptionsHandlerV1x1x0": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SdkOptionsHandlerV2x3x0": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TokensTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}