// WORKAROUND: re-exporting protocol-plugins to give FE access to protocol plugins types
export { Chain } from './implementation/Chain'
export { ChainsManagerClient } from './implementation/ChainsManager'
export { makeSDK } from './implementation/MakeSDK'
export { makeSDKWithSigner } from './implementation/MakeSDKWithSigner'
export { PortfolioManager } from './implementation/PortfolioManager'
export { ProtocolsManagerClient } from './implementation/ProtocolsManagerClient'
export { SDKManager } from './implementation/SDKManager'
export { SDKManagerWithSigner } from './implementation/SDKManagerWithSigner'
export { TokensManagerClient } from './implementation/TokensManagerClient'
export { UserClient } from './implementation/UserClient'
export { UsersManager } from './implementation/UsersManager'
export { OrdersManagerClient } from './implementation/OrdersManagerClient'
export type { IChain } from './interfaces/IChain'
export type { IChainsManagerClient } from './interfaces/IChainsManager'
export type { IOrdersManagerClient } from './interfaces/IOrdersManagerClient'
export type { IPortfolioManager } from './interfaces/IPortfolioManager'
export type { IProtocolsManagerClient } from './interfaces/IProtocolsManagerClient'
export type { ISDKManager } from './interfaces/ISDKManager'
export type { ITokensManagerClient } from './interfaces/ITokensManagerClient'
export type { IUserClient } from './interfaces/IUserClient'
export type { IUsersManager } from './interfaces/IUsersManager'
export type { ISimulatorClient } from './interfaces/simulations/ISimulatorClient'
export { SimulatorClient } from './implementation/simulations/SimulatorClient'
export { PositionUtils } from './utils/PositionUtils'

export * from './reexports'
