import { z } from 'zod'

/**
 * @enum YieldType
 * Indicates the type of yield generated by a protocol
 */
export enum YieldType {
  /** Rebase token: The token balance increases in the user wallet */
  Rebasing = 'Rebasing',
  /** Value accruing token: The token value increases relative to the underlying token */
  ValueAccruing = 'ValueAccruing',
  /** Claimable token: The yield is paid in a secondary reward token requiring a claim transaction */
  Claimable = 'Claimable',
}

/**
 * Zod schema for YieldType
 */
export const YieldTypeSchema = z.nativeEnum(YieldType)

/**
 * Type for the data part of YieldType
 */
export type IYieldTypeData = Readonly<z.infer<typeof YieldTypeSchema>>

/**
 * Type guard for YieldType
 * @param maybeYieldType Object to be checked
 * @returns true if the object is a YieldType
 */
export function isYieldType(maybeYieldType: unknown): maybeYieldType is YieldType {
  return YieldTypeSchema.safeParse(maybeYieldType).success
}
